### PR TITLE
Add 'Besluit AGB/APB over retributies' form

### PR DESCRIPTION
**Pull request by wolfderechter**
## ID
DL-5977

## Description

Add the 'Besluit APB over retributies' form

## Links to other PR's

- https://github.com/lblod/app-digitaal-loket/pull/603

### CODE REVIEW

**Review by Riadabd — APPROVED** [review]
Imported a test submission from Loket, and it showed up as expected :+1: 

Can we keep this ticket in an approved but PR state until the cutover is done? This way we can push things that are currently in dev and master branches and start pushing releases.

**Comment by wolfderechter** [comment]
> Imported a test submission from Loket, and it showed up as expected 👍
> 
> Can we keep this ticket in an approved but PR state until the cutover is done? This way we can push things that are currently in dev and master branches and start pushing releases.

Sure it's not a high prio ticket anyway just needed to be done, just ping me when I can start merging and release

**Comment by Riadabd** [comment]
> > Imported a test submission from Loket, and it showed up as expected 👍
> > Can we keep this ticket in an approved but PR state until the cutover is done? This way we can push things that are currently in dev and master branches and start pushing releases.
> 
> Sure it's not a high prio ticket anyway just needed to be done, just ping me when I can start merging and release

Perfect!

**Comment by cecemel** [comment]
Superseded by https://github.com/lblod/app-worship-decisions-database/pull/90
Closing

**Pull request closed without merging**
